id: P004155
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ9078
  title: དབུ་མ་ཐར་འདོད་དེད་དཔོན་
  author: ''
  volumes:
    2a864f2c4c2748679280db2e821e9dd1:
      image_group_id: I1PD97369
      title: ''
      volume_number: 1
      total_pages: 296
