id: I1946DDE5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:55:10+00:00'
last_modified: '2022-06-07T20:39:34.232944+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ9078
  title: དབུ་མ་ཐར་འདོད་དེད་དཔོན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9FA0:
      image_group_id: I1PD97369
      title: ''
      total_pages: 296
      order: 1
      base_file: 9FA0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
