id: I1946DDE5
legacy_id: P004155
ocr_import_info:
  bdrc_scan_id: W2CZ9078
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T06:53:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T16:12:45.714751+00:00'
last_modified: 2022-09-03 00:13:19.554206
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ9078
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ9078
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ཐར་འདོད་དེད་དཔོན།
  author: ཀུན་མཁྱེན་ཆོས་འབྱོར་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9539938869279128
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1PD97369:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD97369
      total_pages: 296
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD97369.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9539938869279128
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
